# Generated by Django 4.1.5 on 2023-01-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dato_usuarios',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45)),
                ('contrasenia', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=45)),
                ('archivo', models.FileField(upload_to='documentos')),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='modalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modalidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='rankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rol_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='doc_generados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_generado', models.FileField(upload_to='documentos')),
                ('fk_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.dato_usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='dato_usuarios',
            name='fk_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.documentos'),
        ),
        migrations.AddField(
            model_name='dato_usuarios',
            name='fk_rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.rol_usuarios'),
        ),
        migrations.CreateModel(
            name='dato_tutores',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('nro_tutorados', models.IntegerField(null=True)),
                ('ses_individuales', models.IntegerField(null=True)),
                ('ses_grupales', models.IntegerField(null=True)),
                ('referidos', models.IntegerField(null=True)),
                ('atendidos', models.IntegerField(null=True)),
                ('criterio', models.IntegerField(null=True)),
                ('fk_ranking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.rankings')),
                ('fk_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.dato_usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='dato_tutorados',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('ciclo', models.CharField(max_length=2)),
                ('tipo_beca', models.CharField(max_length=45)),
                ('fk_dato_tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.dato_tutores')),
                ('fk_ranking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.rankings')),
                ('fk_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.dato_usuarios')),
                ('modalidad', models.ManyToManyField(to='ranking_tutoria.modalidades')),
            ],
        ),
    ]
