# Generated by Django 4.1.5 on 2023-01-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_tutoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_tutorados',
            name='fk_dato_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.dato_tutores'),
        ),
        migrations.AlterField(
            model_name='dato_tutorados',
            name='fk_ranking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.rankings'),
        ),
        migrations.AlterField(
            model_name='dato_tutorados',
            name='tipo_beca',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='dato_tutores',
            name='atendidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dato_tutores',
            name='criterio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dato_tutores',
            name='fk_ranking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_tutoria.rankings'),
        ),
        migrations.AlterField(
            model_name='dato_tutores',
            name='nro_tutorados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dato_tutores',
            name='referidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dato_tutores',
            name='ses_grupales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dato_tutores',
            name='ses_individuales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
