# Generated by Django 4.1.5 on 2023-01-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_tutoria', '0002_alter_dato_tutorados_fk_dato_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_tutorados',
            name='ciclo',
            field=models.IntegerField(max_length=2),
        ),
    ]
