# Generated by Django 4.1.5 on 2023-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_tutoria', '0003_alter_dato_tutorados_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_tutorados',
            name='ciclo',
            field=models.IntegerField(),
        ),
    ]
